# Generated by Django 3.2.3 on 2021-11-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20211111_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='邮箱', max_length=255, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_index=True, help_text='用户账号', max_length=150, unique=True, verbose_name='用户账号'),
        ),
    ]
