# Generated by Django 3.2.3 on 2021-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0002_auto_20211105_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectmodel',
            name='clean_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='is_bridge',
            field=models.BooleanField(default=False),
        ),
    ]
