# Generated by Django 3.2.3 on 2021-11-04 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plugins.dvadmin_mqtt_iot.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvadmin_mqtt_iot', '0003_auto_20211105_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropModel',
            fields=[
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('clientid', models.CharField(default='', max_length=255)),
                ('node', models.CharField(default='', max_length=255)),
                ('metadata', models.JSONField(default=plugins.dvadmin_mqtt_iot.models.defaultDict)),
                ('event', models.CharField(default='', max_length=255)),
                ('topic', models.CharField(default='', max_length=255)),
                ('qos', models.IntegerField(default=0)),
                ('peerhost', models.CharField(default='', max_length=255)),
                ('publish_received_at', models.DateTimeField(blank=True, null=True)),
                ('pub_props', models.CharField(default='', max_length=255)),
                ('payload', models.CharField(default='', max_length=255)),
                ('_id', models.CharField(default='', max_length=255)),
                ('headers', models.CharField(default='', max_length=255)),
                ('flags', models.CharField(default='', max_length=255)),
                ('reason', models.CharField(default='', max_length=255)),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '消息丢弃',
                'verbose_name_plural': '消息丢弃',
                'db_table': 'dvadmin_mqtt_drop',
                'ordering': ('create_datetime',),
            },
        ),
    ]
