# Generated by Django 3.2.3 on 2021-11-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvadmin_mqtt_iot', '0005_auto_20211106_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='active',
            field=models.BooleanField(default=False, help_text='是否激活', verbose_name='激活'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[(0, '离线'), (1, '在线')], default=0, help_text='元件类型', max_length=4, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='ackmodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='connectmodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='delivermodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='disconnectmodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='dropmodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='subscribemodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='unsubscribemodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.CreateModel(
            name='CellModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, help_text='Id', max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('type', models.CharField(choices=[('lamp', '灯'), ('sensor_temperature', '温度传感器'), ('sensor_moisture', '湿度传感器'), ('sensor_gravity', '重力传感器'), ('driver', '驱动电机')], default='lamp', help_text='元件类型', max_length=32, verbose_name='类型')),
                ('value', models.CharField(default='', help_text='当前值', max_length=5, verbose_name='当前值')),
                ('clientid', models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '物联网设备-元件',
                'verbose_name_plural': '物联网设备-元件',
                'db_table': 'dvadmin_iot_cell',
                'ordering': ('create_datetime',),
            },
        ),
    ]
