# Generated by Django 3.2.3 on 2021-11-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0006_auto_20211108_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmodel',
            name='code',
            field=models.IntegerField(default=0, help_text='编号', verbose_name='编号'),
        ),
    ]
