# Generated by Django 3.2.3 on 2021-11-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dvadmin_mqtt_iot', '0007_cellmodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellmodel',
            options={'ordering': ('type', 'create_datetime'), 'verbose_name': '物联网设备-元件', 'verbose_name_plural': '物联网设备-元件'},
        ),
        migrations.RemoveField(
            model_name='cellmodel',
            name='value',
        ),
        migrations.CreateModel(
            name='CellValueModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, help_text='Id', max_length=255, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('value', models.CharField(default='', help_text='当前值', max_length=5, verbose_name='当前值')),
                ('cellid', models.ForeignKey(db_constraint=False, help_text='元件', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.cellmodel', verbose_name='元件')),
                ('clientid', models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '物联网设备-元件值',
                'verbose_name_plural': '物联网设备-元件值',
                'db_table': 'dvadmin_iot_cvalue',
                'ordering': ('create_datetime',),
            },
        ),
    ]
