# Generated by Django 3.2.3 on 2021-11-08 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0008_auto_20211109_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='active',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('6ada5795-f406-498e-8446-9ec2da5f5fde'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='status',
            field=models.CharField(choices=[(0, '离线'), (1, '在线')], default=0, help_text='设备状态', max_length=4, verbose_name='设备状态'),
        ),
    ]
