# Generated by Django 3.2.3 on 2021-11-08 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0009_auto_20211109_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellvaluemodel',
            name='clientid',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('1506ffb3-5a17-49c2-a574-9d9e9b89041d'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
