# Generated by Django 3.2.3 on 2021-11-08 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0010_auto_20211109_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmodel',
            name='gap',
            field=models.IntegerField(default=60000, help_text='上传间隔毫秒', verbose_name='上传间隔毫秒'),
        ),
        migrations.AddField(
            model_name='cellvaluemodel',
            name='type',
            field=models.CharField(choices=[('control', '控制'), ('status', '状态')], default='status', help_text='类型', max_length=32, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('6ce5b63d-be57-4bea-8f13-84d49e046eae'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
