# Generated by Django 3.2.3 on 2021-11-11 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0013_alter_devicemodel_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('1b85891a-0120-4466-aa1d-c7366e950d82'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
