# Generated by Django 3.2.3 on 2021-11-16 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0014_alter_devicemodel_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmodel',
            name='clientid',
            field=models.ForeignKey(db_constraint=False, help_text='设备名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cell', to='dvadmin_mqtt_iot.devicemodel', verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='cellvaluemodel',
            name='cellid',
            field=models.ForeignKey(db_constraint=False, help_text='元件', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellvalue', to='dvadmin_mqtt_iot.cellmodel', verbose_name='元件'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('d8742c9a-3f40-4197-bbe7-23858fe010c8'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
