# Generated by Django 3.2.3 on 2021-11-16 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0015_auto_20211116_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='type',
            field=models.CharField(choices=[(0, '设备'), (1, '前端')], default=0, help_text='设备类型', max_length=4, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('8cd73dcd-d63f-4cb1-b152-7defcab2b960'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
