# Generated by Django 3.2.3 on 2021-11-16 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0016_auto_20211116_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('4d2a7f4e-2fdd-4d99-b621-969c3855d60b'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
