# Generated by Django 3.2.3 on 2021-11-16 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0017_alter_devicemodel_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.UUID('de6ca2da-fba1-4ffc-97b9-a2bfa612310b'), help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
