# Generated by Django 3.2.3 on 2021-11-16 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dvadmin_mqtt_iot', '0018_alter_devicemodel_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default=uuid.uuid4, help_text='序列号', max_length=255, verbose_name='序列号'),
        ),
    ]
